### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by TPLsmitty** [Esri/time-aware-template#4]
I am getting an error on our Time aware map that says that the user is not signed in. It does not necessarily effect the application, but the error shows up when I look at the site with firebug.

http://tplgis.org/OR/WorkingLands/Apps/TA_LUC/
http://tplgis.org/OR/WorkingLands/Apps/TA_FC/

**Comment by kellyhutchins** [comment]
Its just an internal check we do to see if the user is signed in. Shouldn't cause any app issues.
