### ISSUE TITLE
bug/issue: infowindow popup displays data from other locations than where clicked in map

### ISSUE THREAD

**Issue by bogibrynjar** [Esri/time-aware-template#5]
Greetings!

We have encountered an issue with the time aware web map template where if the user clicks on the map the infowindow pops up even if there is no data displayed there. Furthermore the user can scroll through all the visible features on the map using the arrows in the infowindow top right corner and the infowindow still does not move to the right feature. This is very confusing for the average user because he does not realize that he is looking at data from completely different locations. A live production sample that we are publicly using can be found here:

http://vedur.maps.arcgis.com/apps/OnePane/azuretime/index.html?appid=d8aa500193ff4590ae241e7884ae008f

The infowindow should not in the first place pop up and give information unless there is a feature to be found at the location the user clicks and secondly it should not show information available for more features at that location unless there are more features within the snapping/sensor range threshold where the user clicked on the map.

Thanks in advance.
Cheers!

**Comment by kellyhutchins** [comment]
Probably a css issue in old version of app. Tested with updated source and not happening.
