### ISSUE TITLE
bug/issue: Web app dates above slider not displaying correctly in IE (

### ISSUE THREAD

**Issue by bogibrynjar** [Esri/time-aware-template#6]
Hi @kellyhutchins 

Internet Explorer users are getting a bug where the names of the month are replaced with it's corresponding calender month number (e.g. october is displaying M10). See the image below for further details.

![capture](https://cloud.githubusercontent.com/assets/8677318/4843562/c3c8e438-6033-11e4-86d8-24bc306b6220.PNG)

I tested this myself on Internet Explorer v10.0.9200.17116 and got this result. The web appliction in question was built using the current Time Aware template from the ArcGIS online Gallery. See application here:

http://vedur.maps.arcgis.com/apps/OnePane/azuretime/index.html?appid=da54a233cb0d4b679bdf5a1a860d11b9

Any ideas what could be the cause of the problem?

Cheers!

**Comment by kellyhutchins** [comment]
Closing this since its in old version of app.
