### ISSUE TITLE
"sharinghost" is in default.js, not index.html

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/time-aware-template#8]
The readme states to change the "sharinghost" url in the index.html, but I found "sharinghost" in default.js

**Comment by jgravois** [comment]
thanks for pointing that out.  would you be interested in submitting a pull request to help us correct the problem?  if not, i can shortly.

**Comment by jgravois** [comment]
also, i noticed we're missing a newline above '#Issues', which breaks the markdown formatting.

**Comment by kellyhutchins** [comment]
Looks like this issue is fixed now.
