### ISSUE TITLE
Cumulative display of time-aware data

### ISSUE THREAD

**Issue by yeonkim** [Esri/time-aware-template#9]
I was able to set up a a viewer using time-aware-template (thanks for the template!).
https://gaithersburgmd.maps.arcgis.com/apps/TimeAware/index.html?appid=d82d8be587ca48b7a74a7269a5ba3ccf

Is it possible to show cumulative data during an animation? What I envision is that the data points for previous time periods will  gray out (or change to muted color), and only the data points for the current, active time-period will show in highlighted color. Please let me know if this is possible to achieve with configuration changes. 
If it needs to be custom coded, I appreciate a few pointers on where and what to look for. 

Thanks!
Yeon

**Comment by cghsia** [comment]
Hi Yeon,

About 2 years late, coming from a fellow GIS analyst also utilizing the time-aware template and noticed your question.

Yes, if you open the web map, at the bottom of the screen, if it's time-aware enabled, there will be the time slider and other options.

![image](https://user-images.githubusercontent.com/15991527/60191294-17503600-9802-11e9-946e-e796ed65956e.png)

Click on the options button, on the far right side. With the Time Settings window, click on "Show advanced options".

![image](https://user-images.githubusercontent.com/15991527/60191351-2d5df680-9802-11e9-9f83-01e88c8ee493.png)

From there, click on the "progressively display all data" option in the "As time passes" section.

![image](https://user-images.githubusercontent.com/15991527/60191383-3b137c00-9802-11e9-8481-fe91a5ae49ac.png)

Hope this helps!

**Comment by yeonkim** [comment]
Thanks much for your post! I am sure I checked everywhere back then - maybe I simply missed it, or maybe they didn't have that option then. I will go back and update the setting. :)

Yeon

**Comment by yeonkim** [comment]
I just updated the setting. Thanks again @cghsia!
